#!/bin/bash

cd $(dirname "${0}")
cd ..

BASEROOT="$(jq .source config.json | tr -d '"')"

if [ -z "${1}" ]; then
	VERSIONS=($(jq '.versions[]' config.json | tr -d '"'))
else
	VERSIONS=("${1}")
fi

for VERSION in "${VERSIONS[@]}"; do

	echo "Processing v${VERSION}"

	OUTDIR="data/txt/${VERSION}"
	mkdir -p "${OUTDIR}"

	OUTPUT="${OUTDIR}/addeventlua.txt"
	echo -n > "${OUTPUT}"

	LUAROOT="${BASEROOT}/${VERSION}/lua"
	while read LINE; do

		if [[ "${LINE}" == *'AddEvent()'* ]] || [[ "${LINE}" == *'AddEvent(string)'* ]] ; then
			continue
		fi

		echo "${LINE}" >> "${OUTPUT}"

	done < <(grep -R 'AddEvent(' "${LUAROOT}" --include '*.lua' | cut -f2 -d: | sed 's/^[ ]\+//' | cut -f2 -d'"' | sed 's/--.*$//' | sort -u)
done
