#!/bin/bash

cd $(dirname "${0}")
cd ..

JAVAROOT=$(jq .java.root config.json | tr -d '"')

CORE="$(find "${JAVAROOT}" -name Core.java)"
if [ -z "${CORE}" ]; then
	echo 'Cannot find Core.java!'
	exit
fi

VERSION="$(grep 'new GameVersion' "${CORE}" | cut -f2 -d'(' | awk -F, '{ print $1 $2 }' | tr ' ' '.')"
if [ -z "${VERSION}" ]; then
	echo 'Cannot find game version!'
	exit
fi

OUTPUT1="data/txt/events.txt"
OUTPUT2="data/wiki/events.wiki"
OUTPUT3="data/wiki/eventscurrent.wiki"
OUTPUT4="data/wiki/eventsobsolete.wiki"
echo -n > "${OUTPUT1}"

echo "== Version ${VERSION} ==" | tee "${OUTPUT2}" "${OUTPUT3}" "${OUTPUT4}"
while read LINE; do

	echo "${LINE}" >> "${OUTPUT1}"

	DEPRECATED="$(grep "^${LINE}$" "data/txt/deprecated.txt")"
	if [ -z "${DEPRECATED}" ]; then
		echo "*[[Modding:Lua Events/$LINE|$LINE]]" | tee -a "${OUTPUT2}" "${OUTPUT3}"
	else
		echo "*<s>[[Modding:Lua Events/$LINE|$LINE]]</s>" | tee -a "${OUTPUT2}" "${OUTPUT4}"
	fi

done < <(cat "data/txt/addeventjava.txt" "data/txt/addeventlua.txt" | sort -u)
