#!/bin/bash

cd $(dirname "${0}")
cd ..

if [ -z "${1}" ]; then
	VERSIONS=($(jq '.versions[]' config.json | tr -d '"'))
else
	VERSIONS=("${1}")
fi

for VERSION in "${VERSIONS[@]}"; do

	echo "Processing v${VERSION}"

	OUTDIR1="data/txt/${VERSION}"
	OUTDIR2="data/wiki/${VERSION}"
	mkdir -p "${OUTDIR1}" "${OUTDIR2}"

	OUTPUT1="${OUTDIR1}/events.txt"
	OUTPUT2="${OUTDIR2}/events.wiki"
	OUTPUT3="${OUTDIR2}/eventscurrent.wiki"
	OUTPUT4="${OUTDIR2}/eventsobsolete.wiki"

	echo -n > "${OUTPUT1}"

	echo "== Version ${VERSION} ==" | tee "${OUTPUT2}" "${OUTPUT3}" "${OUTPUT4}" >/dev/null
	while read LINE; do

		echo "${LINE}" >> "${OUTPUT1}"

		DEPRECATED="$(grep "^${LINE}$" "data/txt/deprecated.txt")"
		if [ -z "${DEPRECATED}" ]; then
			echo "*[[Modding:Lua Events/$LINE|$LINE]]" | tee -a "${OUTPUT2}" "${OUTPUT3}" >/dev/null
		else
			echo "*<s>[[Modding:Lua Events/$LINE|$LINE]]</s>" | tee -a "${OUTPUT2}" "${OUTPUT4}" >/dev/null
		fi

	done < <(cat "${OUTDIR1}/addeventjava.txt" "${OUTDIR1}/addeventlua.txt" | sort -u)
done
