#!/bin/bash

cd $(dirname "${0}")
cd ..

JAVAROOT=$(jq .java.root config.json | tr -d '"')

OUTPUT="data/txt/addeventjava.txt"
echo -n > "${OUTPUT}"

while read LINE; do

	if [[ "${LINE}" == *'AddEvent()'* ]] || [[ "${LINE}" == *'AddEvent(string)'* ]] ; then
		continue
	fi

	echo "${LINE}" >> "${OUTPUT}"

done < <((echo OnPlayerCancelTimedAction; grep -R 'AddEvent("' "${JAVAROOT}" --include '*.java') | cut -f2 -d: | sed 's/^[ ]\+//' | cut -f2 -d'"' | sed '' | sort)
