#!/bin/bash

cd $(dirname "${0}")
cd ..

BASEROOT="$(jq .source config.json | tr -d '"')"

if [ -z "${1}" ]; then
	VERSIONS=($(jq '.versions[]' config.json | tr -d '"'))
else
	VERSIONS=("${1}")
fi

for VERSION in "${VERSIONS[@]}"; do

	echo "Processing v${VERSION}"

	OUTDIR="data/txt/${VERSION}"
	mkdir -p "${OUTDIR}"

	OUTPUT="${OUTDIR}/addeventjava.txt"
	echo -n > "${OUTPUT}"

	JAVAROOT="${BASEROOT}/${VERSION}/sources"
	echo $JAVAROOT
	while read LINE; do

		if [[ "${LINE}" == *'AddEvent()'* ]] || [[ "${LINE}" == *'AddEvent(string)'* ]] ; then
			continue
		fi

		echo "${LINE}" >> "${OUTPUT}"

	done < <((echo OnPlayerCancelTimedAction; grep -R 'AddEvent("' "${JAVAROOT}" --include '*.java') | cut -f2 -d: | sed 's/^[ ]\+//' | cut -f2 -d'"' | sed '' | sort -u)
done
