#!/bin/bash

cd $(dirname "${0}")
cd ..

OUTPUT="data/txt/triggerevent.txt"
echo -n > "${OUTPUT}"
while read line; do

	echo $line
	CLASS=$(echo $line | cut -f1 -d';' | sed 's/\$/\\$/g')
	echo $line | sed "s/this/${CLASS}/g" >> "${OUTPUT}"

done < <(cat "data/txt/triggereventjava.txt" "data/txt/triggereventlua.txt" | sort -u)
