#!/bin/bash

cd $(dirname "${0}")
cd ..

if [ -z "${1}" ]; then
	VERSIONS=($(jq '.versions[]' config.json | tr -d '"'))
else
	VERSIONS=("${1}")
fi

for VERSION in "${VERSIONS[@]}"; do

	echo "Processing v${VERSION}"

	OUTDIR="data/txt/${VERSION}"
	mkdir -p "${OUTDIR}"

	OUTPUT="${OUTDIR}/triggerevent.txt"
	echo -n > "${OUTPUT}"

	while read line; do

		echo $line >> "${OUTPUT}"

	done < <(cat "${OUTDIR}/triggereventjava.txt" "${OUTDIR}/triggereventlua.txt" | sort -u)
done
