#!/bin/bash

cd $(dirname "${0}")
cd ..

BASEROOT=$(jq .source config.json | tr -d '"')

if [ -z "${1}" ]; then
	VERSIONS=($(jq '.versions[]' config.json | tr -d '"'))
else
	VERSIONS=("${1}")
fi

for VERSION in "${VERSIONS[@]}"; do

	echo "Processing v${VERSION}"

	OUTDIR="data/txt/${VERSION}"
	mkdir -p "${OUTDIR}"

	OUTPUT="${OUTDIR}/triggereventlua.txt"
	echo -n > "${OUTPUT}"

	LUAROOT="${BASEROOT}/${VERSION}/lua/"
	while read line; do

		CLASS=$(echo $line | cut -f1 -d';' | sed 's/\$/\\$/g')
		echo $line | sed "s/this/${CLASS}/g" | sed 's/;[ ]\+/;/' >> "${OUTPUT}"

	done < <(grep -R 'triggerEvent(' --include '*.lua' "${LUAROOT}" | sed "s#${LUAROOT}##" | grep 'triggerEvent' | sed 's/\//./g' | sed 's/\.lua//' | sed 's/[ ]\+//' | sed 's/triggerEvent[^(]*//' | sed 's/(//' | rev | sed 's/)//' | sed 's/;//' | rev | sed 's/"//' | sed 's/"//' | sed 's/:/;/' | sed 's/,[ ]*/;/g' | sed 's/--.*$//' | tr -d '\r')
done
