#!/bin/bash

cd $(dirname "${0}")
cd ..

ZOMBOIDROOT=$(jq .zomboid.root config.json | tr -d '"')

OUTPUT="data/txt/triggereventlua.txt"
echo -n > "${OUTPUT}"
while read line; do

	echo $line | sed 's/;[ ]\+/;/'
	CLASS=$(echo $line | cut -f1 -d';' | sed 's/\$/\\$/g')
	echo $line | sed "s/this/${CLASS}/g" | sed 's/;[ ]\+/;/' >> "${OUTPUT}"

done < <(grep -R 'triggerEvent(' --include '*.lua' "${ZOMBOIDROOT}" | sed "s#${ZOMBOIDROOT}##" | grep 'triggerEvent' | sed 's/\//./g' | sed 's/\.lua//' | sed 's/[ ]\+//' | sed 's/triggerEvent[^(]*//' | sed 's/(//' | rev | sed 's/)//' | sed 's/;//' | rev | sed 's/"//' | sed 's/"//' | sed 's/:/;/' | sed 's/,[ ]*/;/g' | sed 's/--.*$//' | tr -d '\r')
