#!/bin/bash

cd $(dirname "${0}")
cd ..

BASEROOT=$(jq .source config.json | tr -d '"')

if [ -z "${1}" ]; then
	VERSIONS=($(jq '.versions[]' config.json | tr -d '"'))
else
	VERSIONS=("${1}")
fi

for VERSION in "${VERSIONS[@]}"; do

	echo "Processing v${VERSION}"

	OUTDIR="data/txt/${VERSION}"
	mkdir -p "${OUTDIR}"

	OUTPUT="${OUTDIR}/triggereventjava.txt"
	echo -n > "${OUTPUT}"

	JAVAROOT="${BASEROOT}/${VERSION}/sources/"
	while read line; do

		CLASS=$(echo $line | cut -f1 -d';' | sed 's/\$/\\$/g')
		echo $line | sed "s/this/${CLASS}/g" | sed 's/; /;/' >> "${OUTPUT}"

	done < <(grep -R 'LuaEventManager.triggerEvent\|LuaHookManager.TriggerHook' --include '*.java' "${JAVAROOT}" | sed "s#${JAVAROOT}##" | sed 's/\//./g' | sed 's/\.java//' | sed 's/[ ]\+//' | sed 's/\(LuaEventManager.triggerEvent\|if (!\?LuaHookManager.TriggerHook\)[^(]*//' | grep -v 'Lua.LuaEventManager\|LuaHookManager.TriggerHook' | sed 's/(//' | rev | sed 's/)//' | sed 's/;//' | rev | sed 's/"//' | sed 's/"//' | sed 's/:/;/' | sed 's/,[ ]*/;/g' | sort -u)
done
